export const ALLTWEET_START = 'ALLTWEET_START'
export const ALLTWEET_SUCCESS = 'ALLTWEET_SUCCESS'
export const ALLTWEET_FAILED = 'ALLTWEET_FAILED'

export const SEARCH_START = 'SEARCH_START'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'